import { Food } from '../../shared/models/Food';

export const Foods: Food[] = [
  {
    id: 1,
    name: 'Hamburger',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Amerika'],
    stars: 5,
    imageUrl: '/images/foods/1.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: 2,
    name: 'Sosisli',
    cookTime: '10-20',
    price: 7,
    favorite: true,
    origins: ['Almanya'],
    stars: 4,
    imageUrl: '/images/foods/2.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: 3,
    name: 'Tost',
    cookTime: '10-20',
    price: 4,
    favorite: false,
    origins: ['Türkiye'],
    stars: 4,
    imageUrl: '/images/foods/3.jpg',
    tags: ['FastFood', 'Breakfast'],
  },
  {
    id: 4,
    name: 'Döner',
    cookTime: '10-20',
    price: 8,
    favorite: true,
    origins: ['Türkiye'],
    stars: 5,
    imageUrl: '/images/foods/4.jpg',
    tags: ['FastFood', 'Lunch'],
  },
  {
    id: 5,
    name: 'Kebap',
    cookTime: '10-20',
    price: 15,
    favorite: true,
    origins: ['Türkiye'],
    stars: 4,
    imageUrl: '/images/foods/5.jpg',
    tags: ['FastFood', 'Dinner'],
  },
  {
    id: 6,
    name: 'Tavuk Kanat',
    cookTime: '10-20',
    price: 20,
    favorite: false,
    origins: ['Amerika'],
    stars: 5,
    imageUrl: '/images/foods/6.jpg',
    tags: ['FastFood', 'Dinner'],
  },
];